# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - development
      
pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: '$(Build.SourcesDirectory)/ABVCatalogApp'
    gradleWrapperFile: '$(Build.SourcesDirectory)/ABVCatalogApp/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'
  displayName: gradlew assemble

- script: echo $(Agent.BuildDirectory)
  displayName: 'Run a one-line script'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)/drop'
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'abvcatalog-ci'
  displayName: 'Publish artifact abvcatalog-ci'
  continueOnError: true
