# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - development
      
pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: 'Use dotnet sdk 5.0.x'
  inputs:
    version: 5.0.x

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1
- task: DotNetCoreCLI@2
  displayName: dotnet restore
  inputs:
    command: restore
    projects: '$(System.DefaultWorkingDirectory)/**/*.csproj'
    includeNuGetOrg: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(System.DefaultWorkingDirectory)\BeerRestAPI\*.sln'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: $(System.DefaultWorkingDirectory)\BeerRestAPI\*.sln
    arguments: '--configuration $(BuildConfiguration) --no-incremental --no-restore'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)\BeerRestAPI\bin\$(BuildConfiguration)\netcoreapp3.1
    archiveType: 'zip'
    includeRootFolder: false
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip
    replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Copy infrastructure files to staging directory'
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Infrastructure'
    Contents: 'BeerRestAPI\**\Infrastructure\*'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
